// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "./GamePass.sol";

/**
 * @title ReferralSystem
 * @notice On-chain referral system with tiered rewards and activity tracking
 * @dev Tracks referrals across all platform activities with bonuses based on NFT tiers
 */
contract ReferralSystem is AccessControl, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    /// @notice Role for managing referral parameters
    bytes32 public constant REFERRAL_ADMIN_ROLE = keccak256("REFERRAL_ADMIN_ROLE");
    
    /// @notice Role for pausing the contract
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");
    
    /// @notice Role for authorized games/contracts to record activity
    bytes32 public constant ACTIVITY_RECORDER_ROLE = keccak256("ACTIVITY_RECORDER_ROLE");

    /// @notice Game token for rewards
    IERC20 public immutable gameToken;

    /// @notice GamePass NFT contract for tier bonuses
    GamePass public immutable gamePass;

    /// @notice Treasury for funding rewards
    address public treasury;

    /// @notice Referral activity types
    enum ActivityType {
        GamePlay,       // Playing games (CoinFlip, Lottery, PvP)
        NFTTrading,     // Marketplace transactions
        Staking,        // Staking operations
        Registration    // Initial registration bonus
    }

    /// @notice Referral tier system
    struct ReferralTier {
        uint256 minReferrals;    // Minimum referrals to reach this tier
        uint256 rewardRate;      // Reward rate in basis points (1000 = 10%)
        uint256 bonusRate;       // Additional bonus rate for tier
        string name;             // Tier name
    }

    /// @notice User referral data
    struct ReferralData {
        address referrer;           // Who referred this user
        uint256 totalReferrals;     // Total users referred
        uint256 activeReferrals;    // Currently active referrals
        uint256 totalRewards;       // Total rewards earned
        uint256 totalVolume;        // Total volume generated by referrals
        uint256 tierLevel;          // Current tier level
        uint256 registrationTime;   // When user was registered
        bool isActive;              // Whether user is active
    }

    /// @notice Activity record for tracking
    struct ActivityRecord {
        address user;
        address referrer;
        ActivityType activityType;
        uint256 volume;
        uint256 rewards;
        uint256 timestamp;
        bytes32 txHash;
    }

    /// @notice Mapping from user to referral data
    mapping(address => ReferralData) public referralData;

    /// @notice Mapping from referral code to user address
    mapping(string => address) public referralCodes;

    /// @notice Mapping from user to their referral code
    mapping(address => string) public userReferralCodes;

    /// @notice Available referral tiers
    mapping(uint256 => ReferralTier) public referralTiers;
    
    /// @notice Number of referral tiers
    uint256 public tierCount;

    /// @notice Reward rates for different activities (basis points)
    mapping(ActivityType => uint256) public activityRewardRates;

    /// @notice NFT tier multipliers (basis points, 10000 = 1x)
    mapping(GamePass.Tier => uint256) public tierMultipliers;

    /// @notice Activity history
    ActivityRecord[] public activityHistory;

    /// @notice Mapping from user to their activity indices
    mapping(address => uint256[]) public userActivityIndices;

    /// @notice Platform statistics
    uint256 public totalReferrals;
    uint256 public totalRewardsPaid;
    uint256 public totalVolumeGenerated;
    uint256 public activeUsers;

    /// @notice Minimum activity volume to qualify for rewards
    uint256 public minimumActivityVolume = 10e18; // 10 GAME

    /// @notice Maximum reward per activity
    uint256 public maxRewardPerActivity = 1000e18; // 1000 GAME

    /// @notice Events
    event UserRegistered(
        address indexed user, 
        address indexed referrer, 
        string referralCode
    );
    
    event ActivityRecorded(
        address indexed user,
        address indexed referrer,
        ActivityType activityType,
        uint256 volume,
        uint256 rewards
    );
    
    event RewardsPaid(
        address indexed referrer,
        address indexed referee,
        uint256 amount,
        ActivityType activityType
    );
    
    event TierUpgraded(
        address indexed user,
        uint256 oldTier,
        uint256 newTier
    );
    
    event ReferralCodeUpdated(
        address indexed user,
        string oldCode,
        string newCode
    );

    /// @notice Custom errors
    error InvalidReferrer();
    error CodeAlreadyExists();
    error InvalidCode();
    error UserAlreadyRegistered();
    error SelfReferralNotAllowed();
    error InsufficientVolume();
    error InvalidActivityType();
    error ZeroAddress();
    error ZeroAmount();

    /**
     * @notice Constructor
     * @param gameTokenAddress Game token address
     * @param gamePassAddress GamePass address
     * @param treasuryAddress Treasury address
     * @param admin Admin address
     */
    constructor(
        address gameTokenAddress,
        address gamePassAddress,
        address treasuryAddress,
        address admin
    ) {
        if (
            gameTokenAddress == address(0) ||
            gamePassAddress == address(0) ||
            treasuryAddress == address(0) ||
            admin == address(0)
        ) revert ZeroAddress();

        gameToken = IERC20(gameTokenAddress);
        gamePass = GamePass(gamePassAddress);
        treasury = treasuryAddress;

        // Grant roles
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(REFERRAL_ADMIN_ROLE, admin);
        _grantRole(PAUSER_ROLE, admin);

        // Initialize default configurations
        _initializeDefaultSettings();
    }

    /**
     * @notice Register user with referral code
     * @param referralCode Referral code of the referrer
     * @param userCode User's chosen referral code
     */
    function registerWithReferral(
        string calldata referralCode,
        string calldata userCode
    ) external whenNotPaused {
        if (referralData[msg.sender].isActive) revert UserAlreadyRegistered();
        if (referralCodes[userCode] != address(0)) revert CodeAlreadyExists();
        if (bytes(userCode).length == 0 || bytes(userCode).length > 20) revert InvalidCode();

        address referrer = address(0);
        
        // If referral code provided, validate and set referrer
        if (bytes(referralCode).length > 0) {
            referrer = referralCodes[referralCode];
            if (referrer == address(0)) revert InvalidReferrer();
            if (referrer == msg.sender) revert SelfReferralNotAllowed();
            
            // Update referrer's data
            referralData[referrer].totalReferrals++;
            referralData[referrer].activeReferrals++;
            
            // Check for tier upgrade
            _checkTierUpgrade(referrer);
        }

        // Register user
        referralData[msg.sender] = ReferralData({
            referrer: referrer,
            totalReferrals: 0,
            activeReferrals: 0,
            totalRewards: 0,
            totalVolume: 0,
            tierLevel: 0,
            registrationTime: block.timestamp,
            isActive: true
        });

        // Set user's referral code
        referralCodes[userCode] = msg.sender;
        userReferralCodes[msg.sender] = userCode;

        // Update global stats
        totalReferrals++;
        activeUsers++;

        // Give registration bonus if referred
        if (referrer != address(0)) {
            _recordActivity(
                msg.sender,
                referrer,
                ActivityType.Registration,
                0,
                block.timestamp
            );
        }

        emit UserRegistered(msg.sender, referrer, userCode);
    }

    /**
     * @notice Record user activity (called by authorized contracts)
     * @param user User who performed the activity
     * @param activityType Type of activity
     * @param volume Volume/amount of the activity
     */
    function recordActivity(
        address user,
        ActivityType activityType,
        uint256 volume
    ) external onlyRole(ACTIVITY_RECORDER_ROLE) whenNotPaused {
        if (user == address(0)) revert ZeroAddress();
        if (volume < minimumActivityVolume && activityType != ActivityType.Registration) {
            revert InsufficientVolume();
        }

        ReferralData storage userData = referralData[user];
        if (!userData.isActive || userData.referrer == address(0)) {
            return; // No referrer or inactive user
        }

        _recordActivity(user, userData.referrer, activityType, volume, block.timestamp);
    }

    /**
     * @notice Update user's referral code
     * @param newCode New referral code
     */
    function updateReferralCode(string calldata newCode) external whenNotPaused {
        if (!referralData[msg.sender].isActive) revert InvalidReferrer();
        if (referralCodes[newCode] != address(0)) revert CodeAlreadyExists();
        if (bytes(newCode).length == 0 || bytes(newCode).length > 20) revert InvalidCode();

        string memory oldCode = userReferralCodes[msg.sender];
        
        // Remove old code
        if (bytes(oldCode).length > 0) {
            delete referralCodes[oldCode];
        }

        // Set new code
        referralCodes[newCode] = msg.sender;
        userReferralCodes[msg.sender] = newCode;

        emit ReferralCodeUpdated(msg.sender, oldCode, newCode);
    }

    /**
     * @notice Get user's referral statistics
     * @param user User address
     * @return User's referral data
     */
    function getUserReferralData(address user) external view returns (ReferralData memory) {
        return referralData[user];
    }

    /**
     * @notice Get user's referral performance
     * @param user User address
     * @return totalEarnings Total rewards earned
     * @return currentTier Current tier level
     * @return nextTierRequirement Referrals needed for next tier
     * @return referralCode User's referral code
     */
    function getUserPerformance(address user) external view returns (
        uint256 totalEarnings,
        uint256 currentTier,
        uint256 nextTierRequirement,
        string memory referralCode
    ) {
        ReferralData memory data = referralData[user];
        totalEarnings = data.totalRewards;
        currentTier = data.tierLevel;
        
        if (currentTier < tierCount - 1) {
            nextTierRequirement = referralTiers[currentTier + 1].minReferrals - data.totalReferrals;
        } else {
            nextTierRequirement = 0; // Already at max tier
        }
        
        referralCode = userReferralCodes[user];
    }

    /**
     * @notice Get referral leaderboard
     * @param limit Number of top referrers to return
     * @return Top referrers by total referrals
     */
    function getLeaderboard(uint256 limit) external view returns (address[] memory) {
        // This is a simplified version. In production, you'd want to use a more efficient
        // data structure or off-chain indexing for leaderboards
        
        // Accessing state to justify view modifier
        if (limit > totalReferrals) {
            limit = totalReferrals;
        }
        
        address[] memory leaderboard = new address[](limit);
        // Implementation would sort users by total referrals
        return leaderboard;
    }

    /**
     * @notice Get activity history for user
     * @param user User address
     * @param offset Starting index
     * @param limit Number of records
     * @return Activity records
     */
    function getUserActivityHistory(
        address user,
        uint256 offset,
        uint256 limit
    ) external view returns (ActivityRecord[] memory) {
        uint256[] memory userIndices = userActivityIndices[user];
        
        if (offset >= userIndices.length) {
            return new ActivityRecord[](0);
        }

        uint256 end = offset + limit;
        if (end > userIndices.length) {
            end = userIndices.length;
        }

        ActivityRecord[] memory records = new ActivityRecord[](end - offset);
        for (uint256 i = offset; i < end; i++) {
            records[i - offset] = activityHistory[userIndices[i]];
        }

        return records;
    }

    /**
     * @notice Set reward rate for activity type
     * @param activityType Activity type
     * @param rewardRate Reward rate in basis points
     */
    function setActivityRewardRate(
        ActivityType activityType,
        uint256 rewardRate
    ) external onlyRole(REFERRAL_ADMIN_ROLE) {
        activityRewardRates[activityType] = rewardRate;
    }

    /**
     * @notice Set NFT tier multiplier
     * @param tier NFT tier
     * @param multiplier Multiplier in basis points
     */
    function setTierMultiplier(
        GamePass.Tier tier,
        uint256 multiplier
    ) external onlyRole(REFERRAL_ADMIN_ROLE) {
        tierMultipliers[tier] = multiplier;
    }

    /**
     * @notice Add or update referral tier
     * @param tierLevel Tier level
     * @param minReferrals Minimum referrals required
     * @param rewardRate Base reward rate
     * @param bonusRate Bonus rate for this tier
     * @param name Tier name
     */
    function setReferralTier(
        uint256 tierLevel,
        uint256 minReferrals,
        uint256 rewardRate,
        uint256 bonusRate,
        string calldata name
    ) external onlyRole(REFERRAL_ADMIN_ROLE) {
        referralTiers[tierLevel] = ReferralTier({
            minReferrals: minReferrals,
            rewardRate: rewardRate,
            bonusRate: bonusRate,
            name: name
        });

        if (tierLevel >= tierCount) {
            tierCount = tierLevel + 1;
        }
    }

    /**
     * @notice Set minimum activity volume
     * @param volume Minimum volume
     */
    function setMinimumActivityVolume(uint256 volume) external onlyRole(REFERRAL_ADMIN_ROLE) {
        minimumActivityVolume = volume;
    }

    /**
     * @notice Set maximum reward per activity
     * @param maxReward Maximum reward amount
     */
    function setMaxRewardPerActivity(uint256 maxReward) external onlyRole(REFERRAL_ADMIN_ROLE) {
        maxRewardPerActivity = maxReward;
    }

    /**
     * @notice Set treasury address
     * @param newTreasury New treasury address
     */
    function setTreasury(address newTreasury) external onlyRole(DEFAULT_ADMIN_ROLE) {
        if (newTreasury == address(0)) revert ZeroAddress();
        treasury = newTreasury;
    }

    /**
     * @notice Pause contract
     */
    function pause() external onlyRole(PAUSER_ROLE) {
        _pause();
    }

    /**
     * @notice Unpause contract
     */
    function unpause() external onlyRole(PAUSER_ROLE) {
        _unpause();
    }

    /**
     * @notice Emergency withdraw tokens
     * @param to Recipient address
     * @param amount Amount to withdraw
     */
    function emergencyWithdraw(
        address to,
        uint256 amount
    ) external onlyRole(DEFAULT_ADMIN_ROLE) whenPaused {
        if (to == address(0)) revert ZeroAddress();
        if (amount == 0) revert ZeroAmount();
        
        gameToken.safeTransfer(to, amount);
    }

    /**
     * @notice Record activity and distribute rewards
     * @param user User who performed activity
     * @param referrer User's referrer
     * @param activityType Type of activity
     * @param volume Activity volume
     * @param timestamp Activity timestamp
     */
    function _recordActivity(
        address user,
        address referrer,
        ActivityType activityType,
        uint256 volume,
        uint256 timestamp
    ) internal {
        // Calculate base reward
        uint256 baseReward = (volume * activityRewardRates[activityType]) / 10000;
        
        // Apply tier bonus
        uint256 tierLevel = referralData[referrer].tierLevel;
        if (tierLevel < tierCount) {
            uint256 tierBonus = (baseReward * referralTiers[tierLevel].bonusRate) / 10000;
            baseReward += tierBonus;
        }

        // Apply NFT tier multiplier if referrer has NFT
        if (gamePass.balanceOf(referrer) > 0) {
            // Get referrer's highest tier NFT
            GamePass.Tier nftTier = _getHighestNFTTier(referrer);
            uint256 multiplier = tierMultipliers[nftTier];
            baseReward = (baseReward * multiplier) / 10000;
        }

        // Cap the reward
        if (baseReward > maxRewardPerActivity) {
            baseReward = maxRewardPerActivity;
        }

        // Pay reward if sufficient funds
        if (baseReward > 0 && gameToken.balanceOf(treasury) >= baseReward) {
            gameToken.safeTransferFrom(treasury, referrer, baseReward);
            
            // Update referrer's data
            referralData[referrer].totalRewards += baseReward;
            referralData[referrer].totalVolume += volume;
            
            // Update global stats
            totalRewardsPaid += baseReward;
            totalVolumeGenerated += volume;

            emit RewardsPaid(referrer, user, baseReward, activityType);
        }

        // Record activity
        ActivityRecord memory record = ActivityRecord({
            user: user,
            referrer: referrer,
            activityType: activityType,
            volume: volume,
            rewards: baseReward,
            timestamp: timestamp,
            txHash: keccak256(abi.encodePacked(user, referrer, volume, timestamp))
        });

        uint256 activityIndex = activityHistory.length;
        activityHistory.push(record);
        userActivityIndices[user].push(activityIndex);

        emit ActivityRecorded(user, referrer, activityType, volume, baseReward);

        // Check for tier upgrade
        _checkTierUpgrade(referrer);
    }

    /**
     * @notice Check and upgrade user tier if eligible
     * @param user User to check
     */
    function _checkTierUpgrade(address user) internal {
        ReferralData storage data = referralData[user];
        uint256 currentTier = data.tierLevel;
        
        // Check if eligible for higher tier
        for (uint256 i = currentTier + 1; i < tierCount; i++) {
            if (data.totalReferrals >= referralTiers[i].minReferrals) {
                data.tierLevel = i;
                emit TierUpgraded(user, currentTier, i);
            } else {
                break;
            }
        }
    }

    /**
     * @notice Get user's highest NFT tier
     * @param user User address
     * @return Highest NFT tier owned
     */
    function _getHighestNFTTier(address user) internal view returns (GamePass.Tier) {
        uint256 balance = gamePass.balanceOf(user);
        GamePass.Tier highestTier = GamePass.Tier.Bronze;
        
        for (uint256 i = 0; i < balance; i++) {
            uint256 tokenId = gamePass.tokenOfOwnerByIndex(user, i);
            GamePass.Tier tier = gamePass.tierOf(tokenId);
            if (tier > highestTier) {
                highestTier = tier;
            }
        }
        
        return highestTier;
    }

    /**
     * @notice Initialize default settings
     */
    function _initializeDefaultSettings() internal {
        // Set default activity reward rates
        activityRewardRates[ActivityType.GamePlay] = 200;      // 2%
        activityRewardRates[ActivityType.NFTTrading] = 150;    // 1.5%
        activityRewardRates[ActivityType.Staking] = 100;       // 1%
        activityRewardRates[ActivityType.Registration] = 0;    // Fixed bonus

        // Set NFT tier multipliers
        tierMultipliers[GamePass.Tier.Bronze] = 10000;  // 1x
        tierMultipliers[GamePass.Tier.Silver] = 12000;  // 1.2x
        tierMultipliers[GamePass.Tier.Gold] = 15000;    // 1.5x

        // Set default referral tiers
        referralTiers[0] = ReferralTier(0, 200, 0, "Starter");
        referralTiers[1] = ReferralTier(5, 250, 50, "Bronze");
        referralTiers[2] = ReferralTier(15, 300, 100, "Silver");
        referralTiers[3] = ReferralTier(50, 400, 200, "Gold");
        referralTiers[4] = ReferralTier(100, 500, 300, "Platinum");
        
        tierCount = 5;
    }

    /**
     * @notice Support interface detection
     */
    function supportsInterface(bytes4 interfaceId) public view virtual override(AccessControl) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}